### ISSUE TITLE
Crash when call onDetachedFromActivity

### ISSUE THREAD

**Issue by whyym** [dnaextrim/flutter_ironsource_x#14]
at com.metamorfosis_labs.flutter_ironsource_x.FlutterIronsource_xPlugin.onDetachedFromActivity(FlutterIronsource_xPlugin.kt:311)
at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivity(FlutterEngineConnectionRegistry.java:389)
at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:560)
at io.flutter.embedding.android.FlutterActivity.release(FlutterActivity.java:595)
at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:616)

In FlutterIronsource_xPlugin.kt should not be write TODO, like this: 

  override fun onDetachedFromActivityForConfigChanges() {
    //TODO("Not yet implemented")
  }

  override fun onReattachedToActivityForConfigChanges(binding: ActivityPluginBinding) {
    //TODO("Not yet implemented")
  }

  override fun onDetachedFromActivity() {
    //TODO("Not yet implemented")
  }

**Comment by bylbaboy** [comment]
The same problem
A lot of crashes on production

`kotlin.NotImplementedError: 
  at com.metamorfosis_labs.flutter_ironsource_x.FlutterIronsource_xPlugin.onDetachedFromActivity (FlutterIronsource_xPlugin.kt:311)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivity (FlutterEngineConnectionRegistry.java:389)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach (FlutterActivityAndFragmentDelegate.java:632)
  at io.flutter.embedding.android.FlutterActivity.release (FlutterActivity.java:651)
  at io.flutter.embedding.android.FlutterActivity.onDestroy (FlutterActivity.java:672)
  at android.app.Activity.performDestroy (Activity.java:8048)
  at android.app.Instrumentation.callActivityOnDestroy (Instrumentation.java:1342)
  at android.app.ActivityThread.performDestroyActivity (ActivityThread.java:4927)
  at android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:4971)
  at android.app.servertransaction.DestroyActivityItem.execute (DestroyActivityItem.java:44)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2017)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7397)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:935)`

**Comment by ahammamlho** [comment]
The same error on production

**Comment by mzarhou** [comment]
I have the same problem

**Comment by debugerer** [comment]
The same problem 
A lot of crashes on production.

How to fix this?

**Comment by ahammamlho** [comment]
@debugerer  look at [up](https://github.com/dnaextrim/flutter_ironsource_x/pull/15/commits/c7dbb552c5ede544a34d8d0eda89622fdbba394e)
change \: 
        flutter_ironsource_x: ^0.0.5
to \:
     flutter_ironsource_x:
        git:
           url: https://github.com/dnaextrim/flutter_ironsource_x
           ref: c7dbb552c5ede544a34d8d0eda89622fdbba394e

**Comment by dnaextrim** [comment]
Sorry for my slow response. I forgot to publish this fix to pub.dev. Thanks to @bylbaboy for the solution of this problem, this problem probably happened because I accidentally did todo in AndroidStudio
