### ISSUE TITLE
Not working as a mediation with Meta/Facebook Audience Network

### ISSUE THREAD

**Issue by shahbazhashmi** [dnaextrim/flutter_ironsource_x#21]
How can I use it as a mediation with Meta/Facebook Audience Network. I tried but get below error. You should make it more generic so it can be used with any ads.

`E/AndroidRuntime(22462): ******************************************************************************
E/AndroidRuntime(22462): * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
E/AndroidRuntime(22462): * should follow the instructions here:                                       *
E/AndroidRuntime(22462): * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
E/AndroidRuntime(22462): * to add a valid App ID inside the AndroidManifest.                          *
E/AndroidRuntime(22462): * Google Ad Manager publishers should follow instructions here:              *
E/AndroidRuntime(22462): * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
E/AndroidRuntime(22462): ******************************************************************************
E/AndroidRuntime(22462): 
E/AndroidRuntime(22462): 
E/AndroidRuntime(22462): 	at android.app.ActivityThread.installProvider(ActivityThread.java:7194)
E/AndroidRuntime(22462): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6672)
E/AndroidRuntime(22462): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6567)
E/AndroidRuntime(22462): 	at android.app.ActivityThread.access$1400(ActivityThread.java:224)
E/AndroidRuntime(22462): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
E/AndroidRuntime(22462): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(22462): 	at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(22462): 	at android.app.ActivityThread.main(ActivityThread.java:7562)
E/AndroidRuntime(22462): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22462): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(22462): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(22462): Caused by: java.lang.IllegalStateException: 
E/AndroidRuntime(22462): 
E/AndroidRuntime(22462): ******************************************************************************
E/AndroidRuntime(22462): * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
E/AndroidRuntime(22462): * should follow the instructions here:                                       *
E/AndroidRuntime(22462): * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
E/AndroidRuntime(22462): * to add a valid App ID inside the AndroidManifest.                          *
E/AndroidRuntime(22462): * Google Ad Manager publishers should follow instructions here:              *
E/AndroidRuntime(22462): * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
E/AndroidRuntime(22462): ******************************************************************************
`

**Comment by 92sajid110** [comment]
any help

**Comment by vishalknishad** [comment]
Looks like this plugin is dead

**Comment by 92sajid110** [comment]
did anyone find solution
